
# SEO settings
title: "MIQBALHAKIM's GitHub"
title2: "miqbalhakim" # default: ""
description: "MIQBALHAKIM's technical writing."
keywords: "miqbalhakim, iqbal, hakim, iqbal hakim, github, amtis, melaka, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://miqbalhakim.github.io # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-89993256-2
repo: http://github.com/miqbalhakim
disqus_shortname: "hnbloggithub"
twitter_username: "HeiswayiNrird"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Muhamad Iqbal Hakim"
  job      : "Junior Programmer"
  bio      : "I love coding. I hate coding. They make me confusing."
  thumb    : /images/author.jpg
  email    : miqbalhakim05@gmail.com
  url      : http://miqbalhakim.github.io
  github   : http://github.com/miqbalhakim
  twitter  : http://twitter.com/miqbalhakim05
  facebook : https://www.facebook.com/miqbalhakim05
  linkedin : http://linkedin.com/in/miqbalhakim

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@miqbalhakim05"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
